### ISSUE TITLE
how to get the 4.42 chamfer loss as stated in the paper

### ISSUE THREAD

**Issue by jvzihaha** [val-iisc/capnet#2]
Hi, I have run the code using the default parameters( epoch to 100, batch size = 1, n_view=4) and run the metrics.py to calculate the chamfer loss. But I only can get chamfer loss x100= 5.8  
How to get chamfer lossx100=4.42 as stated in the paper?
Thank you very much.

**Comment by klnavaneet** [comment]
Hi. The  Chamfer metrics reported in the paper were computed with Euclidean distance instead of the squared Euclidean used in this repository. This might be the reason for the difference in the numbers obtained by you and those in the paper. I believe the value of 5.8 for chair is correct (a value of 5.6 was reported by someone else who used our code). In case of comparison with our work, please report the metrics obtained using this repo.
